"""Unit tests for backend models."""
import pytest
import uuid
from unittest.mock import Mock, patch
from datetime import datetime, timedelta

from backend.models.session import Session as SessionModel
from backend.models.user import User
from backend.models.quote import Quote
from backend.models.quote_item import QuoteItem
from backend.models.quote_group import QuoteGroup
from backend.models.budget import Budget
from backend.config.settings import SESSION_TIMEOUT


class TestSessionModel:
    """Tests for Session model."""
    
    @patch('backend.models.session.datetime')
    def test_session_init_sets_expires_at(self, mock_datetime):
        """Test Session initialization sets expires_at."""
        now = datetime(2024, 1, 1, 12, 0, 0)
        mock_datetime.utcnow.return_value = now
        
        session = SessionModel(
            user_id="user-123",
            access_key="access_key",
            secret_key="secret_key",
            region="eu-west-2"
        )
        
        assert session.expires_at == now + timedelta(seconds=SESSION_TIMEOUT)
    
    def test_update_activity(self):
        """Test update_activity updates last_activity and extends expiration."""
        now = datetime(2024, 1, 1, 12, 0, 0)
        
        session = SessionModel(
            user_id="user-123",
            access_key="key",
            secret_key="secret",
            region="eu-west-2",
            expires_at=now + timedelta(seconds=SESSION_TIMEOUT),
            last_activity=now
        )
        original_expires = session.expires_at
        original_last_activity = session.last_activity
        
        # Wait a tiny bit to ensure time difference
        import time
        time.sleep(0.01)
        
        session.update_activity()
        
        # last_activity should be updated to a later time
        assert session.last_activity > original_last_activity
        assert session.expires_at > original_expires
        assert session.updated_at is not None
    
    @patch('backend.models.session.datetime')
    def test_is_expired_false(self, mock_datetime):
        """Test is_expired returns False for active session."""
        now = datetime(2024, 1, 1, 12, 0, 0)
        mock_datetime.utcnow.return_value = now
        
        session = SessionModel(
            user_id="user-123",
            access_key="key",
            secret_key="secret",
            region="eu-west-2",
            expires_at=now + timedelta(seconds=SESSION_TIMEOUT)
        )
        
        assert session.is_expired() is False
    
    @patch('backend.models.session.datetime')
    def test_is_expired_true(self, mock_datetime):
        """Test is_expired returns True for expired session."""
        now = datetime(2024, 1, 1, 12, 0, 0)
        later = now + timedelta(seconds=SESSION_TIMEOUT + 1)
        mock_datetime.utcnow.return_value = later
        
        session = SessionModel(
            user_id="user-123",
            access_key="key",
            secret_key="secret",
            region="eu-west-2",
            expires_at=now + timedelta(seconds=SESSION_TIMEOUT)
        )
        
        assert session.is_expired() is True
    
    def test_to_dict(self):
        """Test to_dict excludes sensitive data."""
        session = SessionModel(
            user_id="user-123",
            access_key="access_key",
            secret_key="secret_key",
            region="eu-west-2"
        )
        
        result = session.to_dict()
        
        assert "session_id" in result
        assert "user_id" in result
        assert "region" in result
        assert "access_key" not in result
        assert "secret_key" not in result


class TestUserModel:
    """Tests for User model."""
    
    def test_user_init(self):
        """Test User initialization."""
        user = User(
            account_id="account-123",
            access_key="access_key",
            is_active=True  # Explicitly set since default may not apply in test
        )
        
        assert user.account_id == "account-123"
        assert user.access_key == "access_key"
        # user_id is generated by default, but may be None until saved to DB
        # In SQLAlchemy, default values are applied when the object is persisted
        # For testing, we just verify the object was created
        assert hasattr(user, 'user_id')
        assert user.is_active is True
    
    def test_user_to_dict(self):
        """Test User to_dict method."""
        user = User(
            account_id="account-123",
            access_key="access_key"
        )
        
        result = user.to_dict()
        
        assert "user_id" in result
        assert "account_id" in result
        assert "is_active" in result


class TestQuoteModel:
    """Tests for Quote model."""
    
    def test_quote_init(self):
        """Test Quote initialization."""
        quote = Quote(
            name="Test Quote",
            user_id="user-123",
            status="active",
            duration=1.0,
            duration_unit="months",
            global_discount_percent=0.0
        )
        
        assert quote.name == "Test Quote"
        assert quote.user_id == "user-123"
        assert quote.status == "active"
        assert quote.duration == 1.0
        assert quote.duration_unit == "months"
        assert quote.global_discount_percent == 0.0
    
    @patch('backend.services.cost_calculator.calculate_quote_total')
    def test_quote_to_dict(self, mock_calc):
        """Test Quote to_dict includes calculation."""
        quote = Quote(
            name="Test Quote",
            user_id="user-123",
            status="active",
            duration=1.0
        )
        quote.items = []
        
        mock_calc.return_value = {"total": 100.0}
        
        result = quote.to_dict()
        
        assert "quote_id" in result
        assert "name" in result
        assert "status" in result
        assert "calculation" in result
        assert result["calculation"]["total"] == 100.0


class TestQuoteItemModel:
    """Tests for QuoteItem model."""
    
    def test_quote_item_init(self):
        """Test QuoteItem initialization."""
        quote_id = str(uuid.uuid4())
        item = QuoteItem(
            quote_id=quote_id,
            resource_name="VM",
            resource_type="compute",
            resource_data='{"Category": "compute"}',
            quantity=1.0,
            unit_price=0.1,
            region="eu-west-2"
        )
        
        assert item.quote_id == quote_id
        assert item.resource_name == "VM"
        assert item.resource_type == "compute"
        assert item.quantity == 1.0
        assert item.unit_price == 0.1
        assert item.region == "eu-west-2"
    
    def test_get_resource_data(self):
        """Test get_resource_data parses JSON."""
        quote_id = str(uuid.uuid4())
        item = QuoteItem(
            quote_id=quote_id,
            resource_name="VM",
            resource_type="compute",
            resource_data='{"Category": "compute", "Type": "VM"}',
            quantity=1.0,
            unit_price=0.1,
            region="eu-west-2"
        )
        
        result = item.get_resource_data()
        
        assert isinstance(result, dict)
        assert result["Category"] == "compute"
        assert result["Type"] == "VM"
    
    def test_get_resource_data_invalid_json(self):
        """Test get_resource_data handles invalid JSON."""
        quote_id = str(uuid.uuid4())
        item = QuoteItem(
            quote_id=quote_id,
            resource_name="VM",
            resource_type="compute",
            resource_data="invalid json",
            quantity=1.0,
            unit_price=0.1,
            region="eu-west-2"
        )
        
        result = item.get_resource_data()
        
        assert result == {}
    
    def test_set_resource_data(self):
        """Test set_resource_data stores JSON."""
        quote_id = str(uuid.uuid4())
        item = QuoteItem(
            quote_id=quote_id,
            resource_name="VM",
            resource_type="compute",
            resource_data="{}",
            quantity=1.0,
            unit_price=0.1,
            region="eu-west-2"
        )
        
        item.set_resource_data({"Category": "compute"})
        
        assert "Category" in item.get_resource_data()
    
    def test_get_parameters(self):
        """Test get_parameters parses JSON."""
        quote_id = str(uuid.uuid4())
        item = QuoteItem(
            quote_id=quote_id,
            resource_name="VM",
            resource_type="compute",
            resource_data="{}",
            quantity=1.0,
            unit_price=0.1,
            region="eu-west-2",
            parameters='{"key": "value"}'
        )
        
        result = item.get_parameters()
        
        assert isinstance(result, dict)
        assert result["key"] == "value"
    
    def test_set_parameters_none(self):
        """Test set_parameters with None."""
        quote_id = str(uuid.uuid4())
        item = QuoteItem(
            quote_id=quote_id,
            resource_name="VM",
            resource_type="compute",
            resource_data="{}",
            quantity=1.0,
            unit_price=0.1,
            region="eu-west-2"
        )
        
        item.set_parameters(None)
        
        assert item.parameters is None
    
    def test_to_dict(self):
        """Test QuoteItem to_dict."""
        quote_id = str(uuid.uuid4())
        item = QuoteItem(
            quote_id=quote_id,
            resource_name="VM",
            resource_type="compute",
            resource_data='{"Category": "compute"}',
            quantity=1.0,
            unit_price=0.1,
            region="eu-west-2"
        )
        
        result = item.to_dict()
        
        assert "id" in result
        assert result["resource_name"] == "VM"
        assert result["resource_type"] == "compute"
        assert result["quantity"] == 1.0
        assert result["unit_price"] == 0.1


class TestBudgetModel:
    """Tests for Budget model."""
    
    def test_budget_init(self):
        """Test Budget initialization."""
        budget = Budget(
            user_id="user-123",
            name="Monthly Budget",
            amount=1000.0,
            period_type="monthly",
            start_date=datetime(2024, 1, 1).date(),
            end_date=datetime(2024, 1, 31).date()
        )
        
        assert budget.user_id == "user-123"
        assert budget.name == "Monthly Budget"
        assert budget.amount == 1000.0
        assert budget.period_type == "monthly"
        assert budget.start_date == datetime(2024, 1, 1).date()
        assert budget.end_date == datetime(2024, 1, 31).date()
    
    def test_budget_to_dict(self):
        """Test Budget to_dict."""
        budget = Budget(
            user_id="user-123",
            name="Monthly Budget",
            amount=1000.0,
            period_type="monthly",
            start_date=datetime(2024, 1, 1).date(),
            end_date=datetime(2024, 1, 31).date()
        )
        
        result = budget.to_dict()
        
        assert "budget_id" in result
        assert result["name"] == "Monthly Budget"
        assert result["amount"] == 1000.0
        assert result["period_type"] == "monthly"
        assert "start_date" in result
        assert "end_date" in result


class TestQuoteModelEnhanced:
    """Enhanced tests for Quote model."""
    
    def test_quote_status_constraint_active(self):
        """Test Quote with valid 'active' status."""
        quote = Quote(
            name="Test Quote",
            user_id="user-123",
            status="active"
        )
        assert quote.status == "active"
    
    def test_quote_status_constraint_saved(self):
        """Test Quote with valid 'saved' status."""
        quote = Quote(
            name="Test Quote",
            user_id="user-123",
            status="saved"
        )
        assert quote.status == "saved"
    
    def test_quote_default_values(self):
        """Test Quote default values."""
        quote = Quote(
            name="Test Quote",
            user_id="user-123",
            status="active",  # Explicitly set since defaults apply at DB level
            duration=1.0,
            duration_unit="months",
            global_discount_percent=0.0
        )
        assert quote.status == "active"
        assert quote.duration == 1.0
        assert quote.duration_unit == "months"
        assert quote.global_discount_percent == 0.0
    
    def test_quote_discount_percent_range(self):
        """Test Quote discount percent within valid range."""
        quote = Quote(
            name="Test Quote",
            user_id="user-123",
            global_discount_percent=50.0
        )
        assert quote.global_discount_percent == 50.0
    
    def test_quote_to_dict_with_items(self):
        """Test Quote to_dict includes items."""
        quote = Quote(
            name="Test Quote",
            user_id="user-123",
            status="active"
        )
        quote.items = []
        
        with patch('backend.services.cost_calculator.calculate_quote_total') as mock_calc:
            mock_calc.return_value = {"total": 100.0}
            result = quote.to_dict()
            
            assert "items" in result
            assert isinstance(result["items"], list)
            assert "calculation" in result
    
    def test_quote_to_dict_includes_all_fields(self):
        """Test Quote to_dict includes all fields."""
        quote = Quote(
            name="Test Quote",
            user_id="user-123",
            status="active",
            duration=2.0,
            duration_unit="years",
            commitment_period="1year",
            global_discount_percent=10.0
        )
        quote.items = []
        
        with patch('backend.services.cost_calculator.calculate_quote_total') as mock_calc:
            mock_calc.return_value = {"total": 100.0}
            result = quote.to_dict()
            
            assert result["name"] == "Test Quote"
            assert result["duration"] == 2.0
            assert result["duration_unit"] == "years"
            assert result["commitment_period"] == "1year"
            assert result["global_discount_percent"] == 10.0
    
    def test_quote_repr(self):
        """Test Quote __repr__ method."""
        quote = Quote(
            name="Test Quote",
            user_id="user-123",
            status="active"
        )
        repr_str = repr(quote)
        assert "Quote" in repr_str
        assert "Test Quote" in repr_str
        assert "active" in repr_str


class TestQuoteItemModelEnhanced:
    """Enhanced tests for QuoteItem model."""
    
    def test_quote_item_from_dict_basic(self):
        """Test QuoteItem.from_dict with basic data."""
        quote_id = str(uuid.uuid4())
        item_dict = {
            "resource_name": "VM Instance",
            "resource_type": "compute",
            "resource_data": {"Category": "compute"},
            "quantity": 2.0,
            "unit_price": 0.1,
            "region": "eu-west-2"
        }
        
        item = QuoteItem.from_dict(item_dict, quote_id)
        
        assert item.resource_name == "VM Instance"
        assert item.resource_type == "compute"
        assert item.quantity == 2.0
        assert item.unit_price == 0.1
        assert item.region == "eu-west-2"
        assert item.quote_id == quote_id
    
    def test_quote_item_from_dict_generates_id(self):
        """Test QuoteItem.from_dict generates ID if invalid."""
        quote_id = str(uuid.uuid4())
        item_dict = {
            "id": "invalid-id",
            "resource_name": "VM",
            "resource_type": "compute",
            "resource_data": {},
            "quantity": 1.0,
            "unit_price": 0.1,
            "region": "eu-west-2"
        }
        
        item = QuoteItem.from_dict(item_dict, quote_id)
        
        # Should generate new UUID
        assert item.item_id != "invalid-id"
        assert len(item.item_id) == 36  # UUID format
    
    def test_quote_item_from_dict_sanitizes_strings(self):
        """Test QuoteItem.from_dict sanitizes string fields."""
        quote_id = str(uuid.uuid4())
        item_dict = {
            "resource_name": "A" * 300,  # Too long
            "resource_type": "compute",
            "resource_data": {},
            "quantity": 1.0,
            "unit_price": 0.1,
            "region": "eu-west-2"
        }
        
        item = QuoteItem.from_dict(item_dict, quote_id)
        
        # Should be truncated to 255
        assert len(item.resource_name) <= 255
    
    def test_quote_item_from_dict_sanitizes_floats(self):
        """Test QuoteItem.from_dict sanitizes float fields."""
        quote_id = str(uuid.uuid4())
        item_dict = {
            "resource_name": "VM",
            "resource_type": "compute",
            "resource_data": {},
            "quantity": -5.0,  # Negative
            "unit_price": float('nan'),  # NaN
            "region": "eu-west-2"
        }
        
        item = QuoteItem.from_dict(item_dict, quote_id)
        
        # Should use defaults
        assert item.quantity == 1.0  # Default
        assert item.unit_price == 0.0  # Default
    
    def test_quote_item_from_dict_with_iops(self):
        """Test QuoteItem.from_dict with IOPS unit price."""
        quote_id = str(uuid.uuid4())
        item_dict = {
            "resource_name": "Volume",
            "resource_type": "storage",
            "resource_data": {},
            "quantity": 1.0,
            "unit_price": 0.1,
            "iops_unit_price": 0.05,
            "region": "eu-west-2"
        }
        
        item = QuoteItem.from_dict(item_dict, quote_id)
        
        assert item.iops_unit_price == 0.05
    
    def test_quote_item_from_dict_iops_zero_becomes_none(self):
        """Test QuoteItem.from_dict converts zero IOPS to None."""
        quote_id = str(uuid.uuid4())
        item_dict = {
            "resource_name": "Volume",
            "resource_type": "storage",
            "resource_data": {},
            "quantity": 1.0,
            "unit_price": 0.1,
            "iops_unit_price": 0.0,
            "region": "eu-west-2"
        }
        
        item = QuoteItem.from_dict(item_dict, quote_id)
        
        assert item.iops_unit_price is None
    
    def test_quote_item_from_dict_invalid_quote_id(self):
        """Test QuoteItem.from_dict raises error for invalid quote_id."""
        item_dict = {
            "resource_name": "VM",
            "resource_type": "compute",
            "resource_data": {},
            "quantity": 1.0,
            "unit_price": 0.1,
            "region": "eu-west-2"
        }
        
        with pytest.raises(ValueError, match="Invalid quote_id format"):
            QuoteItem.from_dict(item_dict, "invalid-quote-id")
    
    def test_quote_item_to_dict_includes_all_fields(self):
        """Test QuoteItem to_dict includes all fields."""
        quote_id = str(uuid.uuid4())
        item = QuoteItem(
            quote_id=quote_id,
            resource_name="VM",
            resource_type="compute",
            resource_data='{"Category": "compute"}',
            quantity=2.0,
            unit_price=0.1,
            region="eu-west-2",
            parameters='{"key": "value"}',
            iops_unit_price=0.05,
            display_order=1
        )
        
        result = item.to_dict()
        
        assert result["id"] == item.item_id
        assert result["resource_name"] == "VM"
        assert result["resource_type"] == "compute"
        assert result["quantity"] == 2.0
        assert result["unit_price"] == 0.1
        assert result["region"] == "eu-west-2"
        assert result["parameters"]["key"] == "value"
        assert result["iops_unit_price"] == 0.05
        assert result["display_order"] == 1
    
    def test_quote_item_set_parameters_empty_dict(self):
        """Test set_parameters with empty dict becomes None."""
        quote_id = str(uuid.uuid4())
        item = QuoteItem(
            quote_id=quote_id,
            resource_name="VM",
            resource_type="compute",
            resource_data="{}",
            quantity=1.0,
            unit_price=0.1,
            region="eu-west-2"
        )
        
        item.set_parameters({})
        
        assert item.parameters is None
    
    def test_quote_item_repr(self):
        """Test QuoteItem __repr__ method."""
        quote_id = str(uuid.uuid4())
        item = QuoteItem(
            quote_id=quote_id,
            resource_name="VM Instance",
            resource_type="compute",
            resource_data="{}",
            quantity=1.0,
            unit_price=0.1,
            region="eu-west-2"
        )
        
        repr_str = repr(item)
        assert "QuoteItem" in repr_str
        assert "VM Instance" in repr_str


class TestBudgetModelEnhanced:
    """Enhanced tests for Budget model."""
    
    def test_budget_period_type_constraint_monthly(self):
        """Test Budget with valid 'monthly' period type."""
        budget = Budget(
            user_id="user-123",
            name="Monthly Budget",
            amount=1000.0,
            period_type="monthly",
            start_date=datetime(2024, 1, 1).date()
        )
        assert budget.period_type == "monthly"
    
    def test_budget_period_type_constraint_quarterly(self):
        """Test Budget with valid 'quarterly' period type."""
        budget = Budget(
            user_id="user-123",
            name="Quarterly Budget",
            amount=3000.0,
            period_type="quarterly",
            start_date=datetime(2024, 1, 1).date()
        )
        assert budget.period_type == "quarterly"
    
    def test_budget_period_type_constraint_yearly(self):
        """Test Budget with valid 'yearly' period type."""
        budget = Budget(
            user_id="user-123",
            name="Yearly Budget",
            amount=12000.0,
            period_type="yearly",
            start_date=datetime(2024, 1, 1).date()
        )
        assert budget.period_type == "yearly"
    
    def test_budget_amount_positive(self):
        """Test Budget with positive amount."""
        budget = Budget(
            user_id="user-123",
            name="Budget",
            amount=1000.0,
            period_type="monthly",
            start_date=datetime(2024, 1, 1).date()
        )
        assert budget.amount == 1000.0
    
    def test_budget_with_end_date(self):
        """Test Budget with end_date specified."""
        budget = Budget(
            user_id="user-123",
            name="Fixed Budget",
            amount=1000.0,
            period_type="monthly",
            start_date=datetime(2024, 1, 1).date(),
            end_date=datetime(2024, 12, 31).date()
        )
        assert budget.end_date == datetime(2024, 12, 31).date()
    
    def test_budget_without_end_date(self):
        """Test Budget without end_date (None)."""
        budget = Budget(
            user_id="user-123",
            name="Ongoing Budget",
            amount=1000.0,
            period_type="monthly",
            start_date=datetime(2024, 1, 1).date(),
            end_date=None
        )
        assert budget.end_date is None
    
    def test_budget_to_dict_with_end_date(self):
        """Test Budget to_dict with end_date."""
        budget = Budget(
            user_id="user-123",
            name="Budget",
            amount=1000.0,
            period_type="monthly",
            start_date=datetime(2024, 1, 1).date(),
            end_date=datetime(2024, 1, 31).date()
        )
        
        result = budget.to_dict()
        
        assert result["end_date"] == "2024-01-31"
    
    def test_budget_to_dict_without_end_date(self):
        """Test Budget to_dict without end_date."""
        budget = Budget(
            user_id="user-123",
            name="Budget",
            amount=1000.0,
            period_type="monthly",
            start_date=datetime(2024, 1, 1).date(),
            end_date=None
        )
        
        result = budget.to_dict()
        
        assert result["end_date"] is None
    
    def test_budget_repr(self):
        """Test Budget __repr__ method."""
        budget = Budget(
            user_id="user-123",
            name="Test Budget",
            amount=1000.0,
            period_type="monthly",
            start_date=datetime(2024, 1, 1).date()
        )
        
        repr_str = repr(budget)
        assert "Budget" in repr_str
        assert "Test Budget" in repr_str
        assert "monthly" in repr_str


class TestUserModelEnhanced:
    """Enhanced tests for User model."""
    
    def test_user_default_is_active(self):
        """Test User defaults to is_active=True."""
        user = User(
            account_id="account-123",
            access_key="access_key",
            is_active=True  # Explicitly set for test
        )
        assert user.is_active is True
    
    def test_user_is_active_false(self):
        """Test User with is_active=False."""
        user = User(
            account_id="account-123",
            access_key="access_key",
            is_active=False
        )
        assert user.is_active is False
    
    def test_user_last_login_at(self):
        """Test User with last_login_at."""
        login_time = datetime(2024, 1, 1, 12, 0, 0)
        user = User(
            account_id="account-123",
            access_key="access_key",
            last_login_at=login_time
        )
        assert user.last_login_at == login_time
    
    def test_user_to_dict_excludes_access_key(self):
        """Test User to_dict excludes sensitive access_key."""
        user = User(
            account_id="account-123",
            access_key="sensitive-key"
        )
        
        result = user.to_dict()
        
        assert "access_key" not in result
        assert "account_id" in result
    
    def test_user_to_dict_includes_all_safe_fields(self):
        """Test User to_dict includes all safe fields."""
        login_time = datetime(2024, 1, 1, 12, 0, 0)
        user = User(
            account_id="account-123",
            access_key="access_key",
            last_login_at=login_time,
            is_active=False
        )
        
        result = user.to_dict()
        
        assert result["user_id"] == user.user_id
        assert result["account_id"] == "account-123"
        assert result["last_login_at"] == "2024-01-01T12:00:00"
        assert result["is_active"] is False
    
    def test_user_repr(self):
        """Test User __repr__ method."""
        user = User(
            account_id="account-123",
            access_key="access_key"
        )
        
        repr_str = repr(user)
        assert "User" in repr_str
        assert "account-123" in repr_str


class TestSessionModelEnhanced:
    """Enhanced tests for Session model."""
    
    def test_session_init_sets_expires_at_if_not_provided(self):
        """Test Session __init__ sets expires_at if not provided."""
        with patch('backend.models.session.datetime') as mock_datetime:
            now = datetime(2024, 1, 1, 12, 0, 0)
            mock_datetime.utcnow.return_value = now
            
            session = SessionModel(
                user_id="user-123",
                access_key="key",
                secret_key="secret",
                region="eu-west-2"
            )
            
            assert session.expires_at is not None
            assert session.expires_at > now
    
    def test_session_init_uses_provided_expires_at(self):
        """Test Session __init__ uses provided expires_at."""
        expires = datetime(2024, 12, 31, 23, 59, 59)
        session = SessionModel(
            user_id="user-123",
            access_key="key",
            secret_key="secret",
            region="eu-west-2",
            expires_at=expires
        )
        
        assert session.expires_at == expires
    
    def test_session_to_dict_includes_all_fields(self):
        """Test Session to_dict includes all non-sensitive fields."""
        session = SessionModel(
            user_id="user-123",
            access_key="key",
            secret_key="secret",
            region="eu-west-2"
        )
        
        result = session.to_dict()
        
        assert "session_id" in result
        assert "user_id" in result
        assert "region" in result
        assert "created_at" in result
        assert "last_activity" in result
        assert "expires_at" in result
    
    def test_session_repr(self):
        """Test Session __repr__ method."""
        session = SessionModel(
            user_id="user-123",
            access_key="key",
            secret_key="secret",
            region="eu-west-2"
        )
        
        repr_str = repr(session)
        assert "Session" in repr_str
        assert session.user_id in repr_str


class TestQuoteGroupModel:
    """Tests for QuoteGroup model."""
    
    def test_quote_group_init(self):
        """Test QuoteGroup initialization."""
        quote_id = str(uuid.uuid4())
        group_id = str(uuid.uuid4())
        group = QuoteGroup(
            group_id=group_id,
            quote_id=quote_id,
            name="Test Group",
            display_order=0
        )
        
        assert group.group_id == group_id
        assert group.quote_id == quote_id
        assert group.name == "Test Group"
        assert group.display_order == 0
    
    def test_quote_group_to_dict(self):
        """Test QuoteGroup to_dict method."""
        quote_id = str(uuid.uuid4())
        group = QuoteGroup(
            quote_id=quote_id,
            name="Test Group",
            display_order=1
        )
        
        data = group.to_dict()
        
        assert data["group_id"] == group.group_id
        assert data["quote_id"] == quote_id
        assert data["name"] == "Test Group"
        assert data["display_order"] == 1
        assert "created_at" in data
        assert "updated_at" in data
    
    def test_quote_group_from_dict_valid(self):
        """Test QuoteGroup from_dict with valid data."""
        quote_id = str(uuid.uuid4())
        group_id = str(uuid.uuid4())
        
        group = QuoteGroup.from_dict({
            "group_id": group_id,
            "name": "Test Group",
            "display_order": 2
        }, quote_id)
        
        assert group.group_id == group_id
        assert group.quote_id == quote_id
        assert group.name == "Test Group"
        assert group.display_order == 2
    
    def test_quote_group_from_dict_invalid_quote_id(self):
        """Test QuoteGroup from_dict with invalid quote_id."""
        with pytest.raises(ValueError, match="Invalid quote_id format"):
            QuoteGroup.from_dict({"name": "Test"}, "invalid-uuid")
    
    def test_quote_group_from_dict_defaults(self):
        """Test QuoteGroup from_dict with defaults."""
        quote_id = str(uuid.uuid4())
        
        group = QuoteGroup.from_dict({}, quote_id)
        
        assert group.quote_id == quote_id
        assert group.name == "New Group"  # Default name
        assert group.display_order == 0
        assert group.group_id is not None  # Auto-generated
    
    def test_quote_group_from_dict_sanitizes_name(self):
        """Test QuoteGroup from_dict sanitizes name."""
        quote_id = str(uuid.uuid4())
        
        # Test with empty name
        group = QuoteGroup.from_dict({"name": ""}, quote_id)
        assert group.name == "New Group"
        
        # Test with very long name
        long_name = "a" * 300
        group = QuoteGroup.from_dict({"name": long_name}, quote_id)
        assert len(group.name) <= 255
    
    def test_quote_group_from_dict_negative_display_order(self):
        """Test QuoteGroup from_dict handles negative display_order."""
        quote_id = str(uuid.uuid4())
        
        group = QuoteGroup.from_dict({"display_order": -5}, quote_id)
        assert group.display_order == 0  # Should be clamped to 0
    
    def test_quote_group_repr(self):
        """Test QuoteGroup __repr__ method."""
        quote_id = str(uuid.uuid4())
        group_id = str(uuid.uuid4())
        group = QuoteGroup(
            group_id=group_id,
            quote_id=quote_id,
            name="Test Group"
        )
        
        repr_str = repr(group)
        assert "QuoteGroup" in repr_str
        assert group.group_id in repr_str
        assert "Test Group" in repr_str
        assert quote_id in repr_str

